# Generated by Django 2.0.1 on 2018-01-03 03:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donationapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donate',
            new_name='Donation',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='donationmatch',
            options={'verbose_name_plural': 'donation matches'},
        ),
        migrations.AlterModelOptions(
            name='requestmatch',
            options={'verbose_name_plural': 'request matches'},
        ),
    ]
