# Generated by Django 2.0.1 on 2018-01-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0002_auto_20180103_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationmatch',
            old_name='donate',
            new_name='donation',
        ),
    ]
